// =============================================================================
// main.bicep — RG-scoped orchestrator for the svh-dynamic-er-ri lab.
//
// Deploys ONE or MANY secured vHubs based on the `hubs` array parameter.
// Each hub gets: vHub (ExpressRoute routing preference), Azure Firewall Basic,
// firewall policy (allow-all lab rule), spoke VNet, optional Ubuntu VM,
// and an optional ER Gateway.
//
// NOT deployed here (handled by deploy scripts post-Bicep):
//   - Spoke → hub VNet connections
//   - Routing Intent
//   - ER circuits and ER gateway connections
//
// Naming contract (all 1-based index i):
//   vWAN      : ${labPrefix}-vwan
//   Hub       : ${labPrefix}-vhub${i}
//   FW policy : ${labPrefix}-vhub${i}-fwpolicy
//   Firewall  : ${labPrefix}-vhub${i}-azfw
//   ER gateway: ${labPrefix}-vhub${i}-ergw
//   Spoke VNet: ${labPrefix}-spoke${i}  (subnet: main)
//   VM        : ${labPrefix}-vm${i}
//   Key Vault : passed as param (generated by deploy script)
// =============================================================================

targetScope = 'resourceGroup'

// ---------------------------------------------------------------------------
// Parameters
// ---------------------------------------------------------------------------

@description('Prefix applied to all resource names. Default: vwanlab.')
param labPrefix string = 'vwanlab'

@description('Primary Azure region for the vWAN resource, Key Vault, and diagnostics workspace.')
param location string = resourceGroup().location

@description('''
Array of hub configuration objects. Each element drives one secured vHub.

Shape of each element:
  {
    region            : string  — Azure region for the hub (e.g. "eastus")
    hubAddressPrefix  : string  — /23 CIDR for the hub (e.g. "10.10.0.0/23")
    spokeAddressPrefix: string  — /24 CIDR for the spoke VNet (e.g. "10.11.0.0/24")
    subnetPrefix      : string  — /27 CIDR for the main subnet (e.g. "10.11.0.0/27")
    deployErGateway   : bool    — deploy an ExpressRoute Gateway in this hub
    deployVm          : bool    — deploy an Ubuntu VM in the spoke
    vmSize            : string  — (optional) VM size override; falls back to the vmSize param
  }
''')
param hubs array

@description('Resource tags merged with lab defaults on all resources.')
param tags object = {}

@description('VM admin username stored in Key Vault.')
param adminUsername string

@description('VM admin password. Stored in Key Vault; never surfaced in outputs.')
@secure()
param adminPassword string

@description('SSH public key (OpenSSH format). Optional — unused by default. Leave empty to use password-only auth.')
param sshPublicKey string = ''

@description('Default VM size when hub.vmSize is not set. Validated by deploy scripts via pick_vm_sku.')
param vmSize string = 'Standard_B2s'

@description('Globally-unique Key Vault name (generated by deploy script: labPrefixkv + 4 random hex chars).')
param keyVaultName string

@description('Object ID of the deploying principal (az ad signed-in-user show --query id). Grants KV secret access.')
param deployerObjectId string = ''

@description('Enable a Log Analytics workspace for lab diagnostics.')
param enableDiagnostics bool = false

@description('Caller public IP used for the inbound SSH NSG allow rule. Empty string = no rule.')
param allowedSshSourceIp string = ''

@description('Attach a public IP to each VM. Default false (cost + security).')
param attachPublicIp bool = false

// ---------------------------------------------------------------------------
// Merged tags — caller tags + lab-mandatory tags on every resource
// ---------------------------------------------------------------------------

var allTags = union(tags, {
  labName: labPrefix
  purpose: 'lab'
  environment: 'lab'
  createdBy: 'svh-dynamic-er-ri'
})

// ---------------------------------------------------------------------------
// Virtual WAN — single Standard instance. Standard required for secured hubs,
// hub-to-hub routing, ExpressRoute, and Routing Intent.
// ---------------------------------------------------------------------------

module vwan 'modules/vwan.bicep' = {
  name: 'deploy-vwan'
  params: {
    vwanName: '${labPrefix}-vwan'
    location: location
    tags: allTags
  }
}

// ---------------------------------------------------------------------------
// Per-hub: Virtual Hub
// hubRoutingPreference is hardcoded to 'ExpressRoute' in the vhub module.
// ---------------------------------------------------------------------------

module vhubs 'modules/vhub.bicep' = [for (hub, i) in hubs: {
  name: 'deploy-vhub-${i}'
  params: {
    hubName: '${labPrefix}-vhub${i + 1}'
    location: hub.region
    hubAddressPrefix: hub.hubAddressPrefix
    vwanId: vwan.outputs.vwanId
    tags: allTags
  }
}]

// ---------------------------------------------------------------------------
// Per-hub: Firewall Policy (Basic, includes lab allow-all network rule)
// Can start immediately — no hub dependency at the ARM layer.
// ---------------------------------------------------------------------------

module fwpolicies 'modules/firewall-policy.bicep' = [for (hub, i) in hubs: {
  name: 'deploy-fwpolicy-${i}'
  params: {
    policyName: '${labPrefix}-vhub${i + 1}-fwpolicy'
    location: hub.region
    tags: allTags
  }
}]

// ---------------------------------------------------------------------------
// Per-hub: Azure Firewall Basic (AZFW_Hub)
// Depends on hub + policy (implicit via output references).
// Provisioning takes ~30-45 min per hub — deploy scripts poll separately.
// ---------------------------------------------------------------------------

module firewalls 'modules/secured-vhub-firewall.bicep' = [for (hub, i) in hubs: {
  name: 'deploy-azfw-${i}'
  params: {
    firewallName: '${labPrefix}-vhub${i + 1}-azfw'
    location: hub.region
    hubId: vhubs[i].outputs.hubId
    firewallPolicyId: fwpolicies[i].outputs.policyId
    tags: allTags
  }
}]

// ---------------------------------------------------------------------------
// Per-hub: Spoke VNet + NSG
// connectToHub=false — scripts create the connection after hub router is ready.
// ---------------------------------------------------------------------------

module spokevnets 'modules/spoke-vnet.bicep' = [for (hub, i) in hubs: {
  name: 'deploy-spoke-${i}'
  params: {
    spokeName: '${labPrefix}-spoke${i + 1}'
    location: hub.region
    spokeAddressPrefix: hub.spokeAddressPrefix
    subnetPrefix: hub.subnetPrefix
    allowedSshSourceIp: allowedSshSourceIp
    connectToHub: false
    tags: allTags
  }
}]

// ---------------------------------------------------------------------------
// Per-hub (optional): Ubuntu VM in the spoke subnet
// ---------------------------------------------------------------------------

module vms 'modules/ubuntu-vm.bicep' = [for (hub, i) in hubs: if (hub.deployVm) {
  name: 'deploy-vm-${i}'
  params: {
    vmName: '${labPrefix}-vm${i + 1}'
    location: hub.region
    subnetId: spokevnets[i].outputs.subnetId
    adminUsername: adminUsername
    sshPublicKey: sshPublicKey
    adminPassword: adminPassword
    // Per-hub vmSize if present; falls back to the global vmSize param.
    vmSize: hub.?vmSize ?? vmSize
    attachPublicIp: attachPublicIp
    tags: allTags
  }
}]

// ---------------------------------------------------------------------------
// Per-hub (optional): ExpressRoute Gateway
// Only created when hub.deployErGateway=true. Scripts may also create them
// dynamically when mapping ER circuits to hubs at interactive prompts.
// ---------------------------------------------------------------------------

module ergateways 'modules/expressroute-gateway.bicep' = [for (hub, i) in hubs: if (hub.deployErGateway) {
  name: 'deploy-ergw-${i}'
  params: {
    gatewayName: '${labPrefix}-vhub${i + 1}-ergw'
    location: hub.region
    hubId: vhubs[i].outputs.hubId
    tags: allTags
  }
}]

// ---------------------------------------------------------------------------
// Key Vault — stores vm-admin-username and vm-admin-password.
// Access policy grants the deploying user get/list/set/delete on secrets.
// ---------------------------------------------------------------------------

module kv 'modules/keyvault.bicep' = {
  name: 'deploy-kv'
  params: {
    keyVaultName: keyVaultName
    location: location
    deployerObjectId: deployerObjectId
    vmAdminUsername: adminUsername
    vmAdminPassword: adminPassword
    tags: allTags
  }
}

// ---------------------------------------------------------------------------
// Optional: Log Analytics workspace for firewall / diagnostic logs.
// ---------------------------------------------------------------------------

module diagnostics 'modules/diagnostics.bicep' = if (enableDiagnostics) {
  name: 'deploy-diagnostics'
  params: {
    workspaceName: '${labPrefix}-law'
    location: location
    tags: allTags
  }
}

// ---------------------------------------------------------------------------
// Outputs consumed by deploy scripts
// ---------------------------------------------------------------------------

@description('Structured per-hub info: hubName, region, firewallName, hasErGateway, spokeName, vmName.')
output hubOutputs array = [for (hub, i) in hubs: {
  hubName: '${labPrefix}-vhub${i + 1}'
  region: hub.region
  firewallName: '${labPrefix}-vhub${i + 1}-azfw'
  hasErGateway: hub.deployErGateway
  spokeName: '${labPrefix}-spoke${i + 1}'
  vmName: hub.deployVm ? '${labPrefix}-vm${i + 1}' : ''
}]

@description('Virtual WAN resource ID.')
output vwanId string = vwan.outputs.vwanId

@description('Virtual WAN name.')
output vwanName string = vwan.outputs.vwanName

@description('Key Vault name for secret retrieval.')
output keyVaultName string = kv.outputs.keyVaultName

@description('Key Vault URI.')
output keyVaultUri string = kv.outputs.keyVaultUri

@description('Log Analytics workspace resource ID (empty string when diagnostics disabled).')
output diagnosticsWorkspaceId string = enableDiagnostics ? (diagnostics.?outputs.workspaceId ?? '') : ''
