// =============================================================================
// Module: keyvault.bicep
// Purpose: Create a Key Vault and store the dynamically generated VM admin
//          username and password as secrets.
// Notes:   - Password is generated by the deploy wrapper (PowerShell/Bash) and
//            passed in as a secure parameter; it is never echoed to stdout.
//          - An access policy grants the deploying user get/list/set on secrets
//            so they can retrieve the password immediately (e.g., for Serial
//            Console). Falls back to no policy if deployerObjectId is empty.
// =============================================================================

@description('Globally-unique Key Vault name.')
param keyVaultName string

@description('Azure region for the Key Vault.')
param location string

@description('Resource tags.')
param tags object

@description('Entra tenant ID for the vault.')
param tenantId string = subscription().tenantId

@description('Object ID of the deploying user/principal to grant secret access. Empty = no access policy.')
param deployerObjectId string = ''

@description('Generated VM admin username to store.')
param vmAdminUsername string

@description('Generated VM admin password to store (secure).')
@secure()
param vmAdminPassword string

resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  tags: tags
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: tenantId
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
    enableRbacAuthorization: false
    accessPolicies: empty(deployerObjectId) ? [] : [
      {
        tenantId: tenantId
        objectId: deployerObjectId
        permissions: {
          secrets: [
            'get'
            'list'
            'set'
            'delete'
          ]
        }
      }
    ]
  }
}

resource usernameSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'vm-admin-username'
  properties: {
    value: vmAdminUsername
  }
}

resource passwordSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'vm-admin-password'
  properties: {
    value: vmAdminPassword
  }
}

@description('Resource ID of the Key Vault.')
output keyVaultId string = keyVault.id

@description('Name of the Key Vault.')
output keyVaultName string = keyVault.name

@description('Vault URI.')
output keyVaultUri string = keyVault.properties.vaultUri
